;
; File generated by cc65 v 2.19 - Git 1f7318f
;
	.fopt		compiler,"cc65 v 2.19 - Git 1f7318f"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$01
	jsr     pusha0
L0002:	ldy     #$01
	lda     (sp),y
	ora     (sp)
	bne     L0002
	tax
	jmp     incsp2

.endproc

